CREATE TABLE if not exists cdm.dm_courier_ledger (
id serial4 NOT NULL,
courier_id int NOT NULL,
courier_name varchar NOT NULL,
settlement_year smallint NOT NULL,
settlement_month smallint NOT null,
orders_count int not null,
orders_total_sum numeric(14,2) not null default 0,
rate_avg float not null,
order_processing_fee numeric(14, 2) NOT null DEFAULT 0,
courier_order_sum numeric(14, 2) not null default 0,
courier_tips_sum numeric(14, 2) not null default 0,
courier_reward_sum numeric(14, 2) not null default 0,

CONSTRAINT dm_courier_ledger_pkey PRIMARY KEY (id),
CONSTRAINT dm_courier_ledger_settlement_year_check CHECK ( (settlement_year >= 2022) and (settlement_year <= 2052) ),
CONSTRAINT dm_courier_ledger_settlement_month_check CHECK ( ( (settlement_month >= 1) and (settlement_month <= 12) ) ),
CONSTRAINT dm_courier_ledger_orders_count_check CHECK ((orders_count >= 0)),
CONSTRAINT dm_courier_ledger_orders_total_sum_check CHECK ((orders_total_sum >= 0)),
CONSTRAINT dm_courier_ledger_rate_avg_check CHECK (( (rate_avg >= 1) and (rate_avg <= 5) )),
CONSTRAINT dm_courier_ledger_order_processing_fee_check CHECK ((order_processing_fee >= 0 )),
CONSTRAINT dm_courier_ledger_courier_order_sum_check CHECK ((courier_order_sum >= 0) ),
CONSTRAINT dm_courier_ledger_courier_tips_sum_check CHECK ((courier_tips_sum >= 0 )),
CONSTRAINT dm_courier_ledger_courier_reward_sum_check CHECK ((courier_reward_sum >= 0 )),
CONSTRAINT dm_courier_ledger_settlement_date_unique UNIQUE (courier_id, settlement_year, settlement_month)
);